# Generated by Django 2.1 on 2018-08-25 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='登录账号')),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('type', models.CharField(max_length=30, verbose_name='用户组')),
            ],
        ),
    ]
